baseurl = "https://jarz.net"
title = "Tim Jarzombek"

theme = "hugo-coder"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

#disqusShortname = "yourdiscussshortname"

[params]
    author = "Tim Jarzombek"
    description = "Tim Jarzombek's personal website"
    keywords = "blog,developer,personal"
    info = "Software Developer in Indianapolis, Indiana"
    avatarurl = "images/avatar.jpg"
    #footercontent = "Enter a text here."

    dateformat = "January 2, 2006"

    hideCredits = false
    hideCopyright = false
    since = 2020

    # Git Commit in Footer, uncomment the line below to enable it.
    #commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorscheme = "light"

    # Series see also post count
    maxSeeAlsoItems = 5

    # Custom CSS
    custom_css = [ "styles/my.css" ]
    
    # Custom JS
    custom_js = []

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/jarz/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 2
    url = "https://twitter.com/tim_jarz/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 3
    url = "https://www.linkedin.com/in/tjarzombek/"
[[params.social]]
    name = "Email"
    icon = "fa fa-envelope"
    weight = 4
    url = "mailto:tim@jarz.net"

[[menus.main]]
    name = "About"
    weight = 1
    url = "about/"

#[[menus.main]]
#    name = "Blog"
#    weight = 2
#    url = "blog/"
